image: "python:3.8"


before_script:
  - python3 --version
  - pip3 install -r requirements.txt

stages:
  - SCA

static_code_analysis:
  stage: SCA
  script:
    - python3 -m flake8 tests/
    - python3 -m flake8 main/
    - python3 -m pylint tests/
    - python3 -m pylint main/
    - python3 -m pycodestyle tests/
    - python3 -m pycodestyle main/